config/routes.rb
ReportApp::Application.routes.draw do
  resources :users do
    member do
      get :following , :followers, :see_reports
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :reports, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: "static_pages#home"

  match '/report_post',to: "users#report_post"

  match '/search', to: "users#search"

  match '/signup', to:"users#new"

  match '/signin', to:"sessions#new"

  match '/signout', to:"sessions#destroy", via: :delete

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"

  match '/contact', to: "static_pages#contact"

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :followed_id, presence: true
  validates :follower_id, presence: true
  
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Report < ActiveRecord::Base
	attr_accessible :content
	validates :user_id , presence: true
	validates :content , presence: true
	belongs_to :user
	default_scope order: 'reports.created_at DESC' 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :reports, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",class_name:"Relationship",dependent: :destroy
  has_many :followers, through: :reverse_relationships,source: :follower
  
  before_save :downcase_email
  before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  private 
  	def create_remember_token
  		self.remember_token=SecureRandom.urlsafe_base64
  	end

  	def downcase_email
  		self.email=email.downcase
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_requests
  	sign_out
  	super
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_filter :signed_in_user

	def create
		@report = current_user.reports.build(params[:report])
		if @report.save
			flash[:success] = "Report posted!"
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def destroy
		@report.destroy
		render @root_url

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end
	def create
		user=User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error]="Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	@report = current_user.reports.build if signed_in?
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:index,:edit, :update,:following,:followers]
  before_filter :correct_user, only: [:edit,:update,:see_reports]
  before_filter :admin_user, only: [:destroy]
  
  def new
  	@user=User.new
  end

  def show 
  	@user = User.find(params[:id])
    @reports = @user.reports
  end

  def create
  	@user=User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success]= "Welcome to the reporting app"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    #done in before filter
    #@user=User.find(params[:id])
  end

  def update
    #done in before filter
    #@user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Destroyed."
    redirect_to users_url
  end

  def search 
    @ret = User.find_by_name(params[:q])
    render 'shared/search_result'
  end 

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def see_reports
    @title = "Last Report"
    @user = User.find(params[:id])
    @users=@user.followed_users
    
    render 'shared/see_reports'
  end

  private 

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title= "Reporting app"
		page_title.empty? ? base_title : "#{base_title} | #{page_title}"
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user=user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user=nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to]=request.url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user,dimension=80)
		gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name,class: "gravatar",height: dimension,width: dimension)
	end
end

app/views/layouts/_footer.html.erb
<footer class ="footer">
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Reporting app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "See Reports", see_reports_user_path(current_user) if signed_in?%></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class = "container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_report_form.html.erb
<div>
<%= form_for(@report) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Create new report..." %>
  </div>
  <%= f.submit "Submit Report", class: "btn btn-large btn-primary" %>
<% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
	<a href="<%= following_user_path(@user)%>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
    	<strong id="followers" class="stat">
    	  <%= @user.followers.count %>
    	</strong>
    	followers
  	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/shared/search_result.html.erb
<% provide(:title, 'Search result') %>
<h1>All users</h1>
<%= form_tag("/search", method: "get") do %>
	<%= label_tag(:q, "Search by name: ")%>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search") %>
<% end %>
<% if @ret %>
<ul>
   <section>
				<%= link_to(gravatar_for(@ret,50), @ret) %>
				<%= link_to @ret.name, @ret %>
		</section>
</ul>
<% else %>
	<b>No result</b>
<% end %>

app/views/shared/see_reports.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    <section> <%= render 'shared/stats'%> </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |u| %>
          <li>
            <%= gravatar_for(u,40) %>
            <%= link_to u.name, u %>
            <% if u.reports.size > 0 %>
              <span class="content"><%= u.reports.first.content %></span>
              <span class="timestamp">Posted <%= time_ago_in_words(u.created_at)%> ago.</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title,'About us')%>

<h1>About us</h1>
<p>
	This app is built to make the reporting much easier
</p>
 

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>
	Will be updated shortly
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
	This is the help page of the report app, Use the app intutively :-P !!
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <% 2.times do %>
      <br>
    <% end %>
    <i><section class="pull-right" style="font-size:150%;" >Report for: <em><%= Time.now.strftime("%d/%m/%Y") %></em></section></i>
    <% 3.times do %>
      <br>
    <% end %>
      <section>
        <%= render 'shared/report_form' %>
      </section>
  </div>
<% else %>
<div class = "center hero-unit">
	<div>
	<h1>Need simple solution for reporting?</h1>
	<h2>You are one step closer</h2>
	<%= image_tag("report_home_image.jpg",height: 480, width:360) %>
	</div>
	<div>
	<%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
	</div>
</div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
	<div ><%= f.hidden_field :followed_id %></div>
	<%= f.submit "Follow",class: "btn btn-large btn-primary"%>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	<% if current_user.following?(@user) %>
		<%= render 'unfollow'%>
	<% else %>
		<%= render 'follow' %>
	<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,"Edit user") %>
<h1>Make changes to your Profile </h1>

<div class="row6" >
	<div class="span6 offset3">
	<%= form_for(@user) do |f| %>

		<%= render 'shared/error_messages',object: f.object  %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation ,"Confirm password" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	<% end %>

	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users")%>
<h1>All users</h1>
<%= form_tag("/search", method: "get") do %>
	<%= label_tag(:q, "Search by name: ")%>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search") %>
<% end %>
<ul class="users">
	<% @users.each do |user| %>
	<li>
		<%= gravatar_for(user,50) %>
		<%= link_to user.name, user %>
		<% if current_user.admin? && !current_user?(user) %>
			<%= link_to "delete",user,method: :delete,data: {confirm: "you sure? "} %>
		<% end %>
	</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title,'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
	<%= form_for(@user) do |f| %>

		<%= render 'shared/error_messages', object: f.object %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="span8">
		<%= render 'follow_form' if signed_in? %>
		<% if @user.reports.any? %>
			<h3>Reports</h3>
			<ol class="reports">
			<% @reports.each do |rep| %>
			<li>
				<span class="content"><%=rep.content%></span>
				<span class="timestamp">Posted <%= time_ago_in_words(rep.created_at)%> ago.</span>
			</li>
			<% end %>
			</ol>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    <section> <%= render 'shared/stats'%> </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |user| %>
          <li>
            <%= gravatar_for(user,50) %>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>